#-----------------------------------------------------------------
# logsearch.conf - configuration file for Logsearch binary
# 
#-----------------------------------------------------------------
# INCLUDE TAGS
# The search tags, tags are not case-sensitive
#
# I have already included the most common 'attack tags'
#
# NOTE:
# -Adding more include tags will increase the search time
# -Removing tags will make the search faster, but instead you 
#  could miss an attack, remove only if you know what you are doing
# -You can disable a tag by adding '#' (comment sign) in the first column
#
# Character encoding help below:
# %3c = <
# %5c = \
# %2e = .
# %2f = /
# %20 = space
# %3d = =
#---------------------
# SQL injections tags
#---------------------
include=select%20
include=select+
include=select 
include=' or 
include='+or+
include='%20or%20

#-----------------------------
# RFI - Remote file inclusions tags
#-----------------------------
include==http
include=%3dhttp
include=>http
include=&gt;http
include=%3ehttp
include=?http
include=&http
include==ftp
include=%3dftp
include=>ftp
include=&gt;ftp
include=%3eftp
include=?ftp
include=&ftp

#-------------------------
# Local file parsing tags
#-------------------------
include=passwd
include=win.ini
include=win%2eini
include=php.ini
include=php%2eini
include=cmd.exe
include=cmd%2eexe
include=../
include=..%2f
include=..\
include=..%5c
include=%2e./
include=%2e.%2f
include=%2e.\
include=%2e.%5c
include=.%2e/
include=.%2e%2f
include=.%2e\
include=.%2e%5c
include=%2e%2e/
include=%2e%2e%2f
include=%2e%2e\
include=%2e%2e%5c

#---------------------------------
# XSS - cross site scripting tags
#---------------------------------
include=<script
include=%3cscript
include=&lt;script
include=;lt;script
include=%20script
include=javascript
include=.cookie
include=%2ecookie
include=&#

#-----------------------------------------------------------------
# EXCLUDE TAGS
# Tags to be skipped from the search, tags are not case-sensitive
#
# Example 1, some OpenADS scripts that will generate fake alerts:
exclude=/openads/www/delivery/ajs.php?
exclude=/openads/www/delivery/lg.php?
exclude=/openads/www/delivery/ck.php?
exclude=/openads/www/delivery/ai.php?
#
# Example 2, some useless vBulletin attack alerts (v3.6.x or newer): 
#exclude=/showthread.php?p=http
#exclude=/showthread.php?t=http
#exclude=/forumdisplay.php?f=http
#
# NOTE:
# -The '#' is interpreted as start of a comment, remove it to activate a row
# -Adding exclude tags will increase the search time
# -Adding wrong exclude tags can hide some attacks
#-----------------------------------------------------------------
exclude=/showthread.php?p=http
exclude=/showthread.php?t=http
exclude=forumdisplay.php?f=http

#-----------------------------------------------------------------
# IP HITS
# Split the output for attacker-IP:s with more than X hits.
# Only useful if you need to cut and paste the final IP-list
# into another application.
#-----------------------------------------------------------------
ip_hits=2
